repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
      args: ["--profile", "black"]
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      args: [ --max-line-length=120,
              --per-file-ignores=__init__.py:F401,
      ]
