variables:
- group: 'axh-nonprod'
- name: vmImageName
  value: 'ubuntu-latest'
- name: dockerImageName
  value: axh-timescale-streaming
- name: TAG
  value: '$(Build.SourceVersion)'  
- name: dockerRegistryServiceConnection
  value: axh4nonprod4shared4cr
- name: functionAppName
  value: 'axh-stage-appl-timescale-streaming-func'
- name: azureSubscription
  value: 'terraform_nonprod_spi'


pool:
  vmImage: $(vmImageName)

stages:
- stage: Build
  dependsOn: [] 
  displayName: Build
  jobs:
  - job: Build
    displayName: Build

    steps:
    - task: UsePythonVersion@0
      displayName: Use Python 3.8
      inputs:
        versionSpec: 3.8

    - task: Docker@2
      displayName: Build
      inputs:
        command: build
        repository: $(dockerImageName)
        tags: |
          $(TAG)
          latest
        arguments: --secret id=pat,env=PAT
        containerRegistry: $(dockerRegistryServiceConnection)
      env:
        DOCKER_BUILDKIT: 1
        PAT: $(pat)

    - task: Docker@2
      displayName: Push
      inputs:
        command: push
        repository: $(dockerImageName)
        tags: |
          $(TAG)
          latest
        containerRegistry: $(dockerRegistryServiceConnection)

- stage: Deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Deploy
  jobs:
  - job: 
    displayName: Deploy
    steps:
    - task: AzureFunctionAppContainer@1
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: $(functionAppName)
        imageName: 'axh4nonprod4shared4cr.azurecr.io/$(dockerImageName):$(TAG)'
        appSettings: >-
          -TEAMS_URL "https://axpogrp.webhook.office.com/webhookb2/1c7d8e30-f530-4faf-acc0-7ef098a2a388@8619c67c-945a-48ae-8e77-35b1b71c9b98/IncomingWebhook/5b6d6935cb774847950f3f9cd081c0cb/adfeab72-7d9c-4e19-a21b-6781b139b707"
          -LINK_TO_STORAGE_ACCOUNT localhost:8000
          -TIMESCALE_USERNAME "tsdbadmin"
          -TIMESCALE_HOST_URL "axh-lab-appl-timescale-streaming-db-axpo-c52c.a.timescaledb.io"
          -TIMESCALE_PORT 27992
          -TIMESCALE_DATABASE_NAME "iot_db"
          -AZURE_CONTAINER_NAME "missing-sensors"
          


          
