variables:
- group: 'axh-nonprod'
- name: vmImageName
  value: 'ubuntu-latest'
- name: dockerImageName
  value: axh-timescale-streaming
- name: TAG
  value: '$(Build.SourceVersion)'  
- name: dockerRegistryServiceConnection
  value: axh4nonprod4shared4cr
- name: functionAppName
  value: 'axh-stage-appl-streaming-func'
- name: azureSubscription
  value: 'terraform_nonprod_spi'


pool:
  vmImage: $(vmImageName)

stages:
- stage: Build
  dependsOn: [] 
  displayName: Build
  jobs:
  - job: Build
    displayName: Build

    steps:
    - task: UsePythonVersion@0
      displayName: Use Python 3.8
      inputs:
        versionSpec: 3.8

    - task: Docker@2
      displayName: Build
      inputs:
        command: build
        repository: $(dockerImageName)
        tags: |
          $(TAG)
          latest
        arguments: --secret id=pat,env=PAT
        containerRegistry: $(dockerRegistryServiceConnection)
      env:
        DOCKER_BUILDKIT: 1
        PAT: $(pat)

    - task: Docker@2
      displayName: Push
      inputs:
        command: push
        repository: $(dockerImageName)
        tags: |
          $(TAG)
          latest
        containerRegistry: $(dockerRegistryServiceConnection)

- stage: Deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Deploy
  jobs:
  - job: 
    displayName: Deploy
    steps:
    - task: AzureFunctionAppContainer@1
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: $(functionAppName)
        imageName: 'axh4nonprod4shared4cr.azurecr.io/$(dockerImageName):$(TAG)'
        appSettings: >-
          -TEAMS_URL "https://axpogrp.webhook.office.com/webhookb2/1c7d8e30-f530-4faf-acc0-7ef098a2a388@8619c67c-945a-48ae-8e77-35b1b71c9b98/IncomingWebhook/5b6d6935cb774847950f3f9cd081c0cb/adfeab72-7d9c-4e19-a21b-6781b139b707"
          -LINK_TO_STORAGE_ACCOUNT "https://portal.azure.com/#view/Microsoft_Azure_Storage/ContainerMenuBlade/~/overview/storageAccountId/%2Fsubscriptions%2F40eb8351-55ff-4349-9a41-39fdb8eae84b%2FresourceGroups%2Faxh-stage-appl-analytics-rg%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Faxh4stage4appl4timesc4sa/path/missing-sensors/etag/%220x8DA8772B5504F1A%22/defaultEncryptionScope/%24account-encryption-key/denyEncryptionScopeOverride~/false/defaultId//publicAccessVal/None"
          -TIMESCALE_USERNAME "tsdbadmin"
          -TIMESCALE_HOST_URL "axh-prod-appl-timescale-db-axpo-c52c.a.timescaledb.io"
          -TIMESCALE_PORT 27992
          -TIMESCALE_DATABASE_NAME "iot_db"
          -TIMESCALE_PASSWORD @Microsoft.KeyVault(VaultName=axh-stage-appl-analy-kv;SecretName=axh-stage-appl-timescale-pw-secret)
          -AZURE_CONTAINER_NAME "missing-sensors"
          -ASSET_API_BASE "https://axh-stage-appl-app-asset-api.azurewebsites.net"
          -API_CLIENT_ID "azure-func-stage"
          -API_CLIENT_SECRET @Microsoft.KeyVault(VaultName=axh-stage-appl-analy-kv;SecretName=axh-stage-appl-analy-azure-func-api-client-secret)
          -RELOAD_SIGNAL_TABLE True
          -PYTHONHASHSEED 0
          


          
