variables:
- name: vmImageName
  value: 'ubuntu-latest'
- name: dockerImageName
  value: axh-timescale-streaming
- name: TAG
  value: '$(Build.SourceVersion)'


pool:
  vmImage: $(vmImageName)


# ***************** Stage ****************************
stages:
- stage: Build_Azure_Func_Streaming_Stage
  dependsOn: []
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: STAGE Build Az Func
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: UsePythonVersion@0
      displayName: Use Python 3.9
      inputs:
        versionSpec: 3.9
    - task: Docker@2
      displayName: Build
      inputs:
        command: build
        dockerfile: Dockerfile
        repository: $(dockerImageName)
        tags: |
          $(TAG)
          latest
        arguments: --secret id=pat,env=PAT
        containerRegistry: acr_nonprod_service_connection
      env:
        DOCKER_BUILDKIT: 1
        PAT: $(pat)
    - task: Docker@2
      displayName: Push
      inputs:
        command: push
        repository: $(dockerImageName)
        tags: |
          $(TAG)
          latest
        containerRegistry: acr_nonprod_service_connection

- stage: Request_Deployment_Streaming_Stage
  dependsOn: [Build_Azure_Func_Streaming_Stage]
  displayName: STAGE Request Deploy of Streaming Func
  jobs:
  - job: waitForValidation
    displayName: Wait for external validation
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # task times out in 1 day
        inputs:
          notifyUsers: |
            emanuel.joos@axpo.com
          instructions: 'Please validate the build configuration and resume'
          onTimeout: 'resume'

- stage: Deploy_Streaming_Stage
  dependsOn: [Request_Deployment_Streaming_STAGE]
  displayName: Deploy
  jobs:
  - job: 
    displayName: Deploy
    steps:
    - task: AzureFunctionAppContainer@1
      inputs:
        azureSubscription: terraform_nonprod_spi
        appName: axh-stage-appl-streaming-func
        imageName: 'axh4nonprod4shared4cr.azurecr.io/$(dockerImageName):$(TAG)'
        appSettings: >-
          -TIMESCALE_USERNAME "tsdbadmin"
          -TIMESCALE_HOST_URL "axh-prod-appl-timescale-db-axpo-c52c.a.timescaledb.io"
          -TIMESCALE_PORT 27992
          -TIMESCALE_DATABASE_NAME "iot_db"
          -TIMESCALE_PASSWORD @Microsoft.KeyVault(VaultName=axh-stage-appl-analy-kv;SecretName=axh-stage-appl-timescale-pw-secret)
          -ASSET_API_BASE "https://axh-stage-appl-app-asset-api.azurewebsites.net"
          -API_CLIENT_ID "azure-func-stage"
          -API_CLIENT_SECRET @Microsoft.KeyVault(VaultName=axh-stage-appl-analy-kv;SecretName=axh-stage-appl-analy-azure-func-api-client-secret)
          -RELOAD_SIGNAL_TABLE True
          -PYTHONHASHSEED 0
          


# ***************** PROD ****************************

- stage: Build_Azure_Func_Streaming_Prod
  dependsOn: []
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: PROD Build Az Func
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: UsePythonVersion@0
      displayName: Use Python 3.9
      inputs:
        versionSpec: 3.9
    - task: Docker@2
      displayName: Build
      inputs:
        command: build
        dockerfile: Dockerfile
        repository: $(dockerImageName)
        tags: |
          $(TAG)
          latest
        arguments: --secret id=pat,env=PAT
        containerRegistry: acr_prod_service_connection
      env:
        DOCKER_BUILDKIT: 1
        PAT: $(pat)
    - task: Docker@2
      displayName: Push
      inputs:
        command: push
        repository: $(dockerImageName)
        tags: |
          $(TAG)
          latest
        containerRegistry: acr_prod_service_connection

- stage: Request_Deployment_Streaming_Prod
  dependsOn: [Build_Azure_Func_Streaming_Prod]
  displayName: PROD Request Deploy of Streaming Func
  jobs:
  - job: waitForValidation
    displayName: Wait for external validation
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # task times out in 1 day
        inputs:
          notifyUsers: |
            emanuel.joos@axpo.com
          instructions: 'Please validate the build configuration and resume'
          onTimeout: 'resume'

- stage: Deploy_Streaming_Prod
  dependsOn: [Request_Deployment_Streaming_Prod]
  displayName: Deploy
  jobs:
  - job:
    displayName: Deploy
    steps:
    - task: AzureFunctionAppContainer@1
      inputs:
        azureSubscription: terraform_prod_spi
        appName: axh-prod-appl-streaming-func
        imageName: 'axh4prod4shared4cr.azurecr.io/$(dockerImageName):$(TAG)'
        appSettings: >-
          -TIMESCALE_USERNAME "tsdbadmin"
          -TIMESCALE_HOST_URL "axh-lab-appl-timescale-streaming-db-axpo-c52c.a.timescaledb.io"
          -TIMESCALE_PORT 27992
          -TIMESCALE_DATABASE_NAME "iot_db"
          -TIMESCALE_PASSWORD @Microsoft.KeyVault(VaultName=axh-prod-appl-analy-kv;SecretName=axh-prod-appl-timescale-pw-secret)
          -ASSET_API_BASE "https://axh-stage-appl-app-asset-api.azurewebsites.net"
          -API_CLIENT_ID "azure-func-stage"
          -API_CLIENT_SECRET @Microsoft.KeyVault(VaultName=axh-prod-appl-analy-kv;SecretName=axh-prod-appl-analy-azure-func-api-client-secret)
          -RELOAD_SIGNAL_TABLE True
          -PYTHONHASHSEED 0